spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_db
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jooq:
    sql-dialect: MYSQL

  flyway:
    enabled: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

server:
  port: 8080


security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    issuer: https://azki.ir
    audience: azki.ir

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.reservation: DEBUG
